<?php
/**
 * Created by PhpStorm.
 * User: igroc
 * Date: 10.09.2018
 * Time: 12:04
 */

namespace frontend\modules\api\models;


class Project extends \common\models\Project
{

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }
}